# Example shown in the session for bind-mount with init container via Docker Compose
---
services:
  init-gateway:
    image: inductiveautomation/ignition:latest
    entrypoint: sh -c
    volumes:
      # We mount this in the container as `/data` to not conflict with built-in files
      # at `/usr/local/bin/ignition/data`
      - ./gateway-data:/data
    networks:
      - network
    command:
      # Seed the files from the image to our /data if marker file not present, skip
      # if the marker file exists (and implicitly exit cleanly with status code 0)
      - |
        if [ ! -f /data/.ignition-seed-complete ]; then
          touch /data/.ignition-seed-complete ;
          cp -dpR /usr/local/bin/ignition/data/* /data/ ;
        fi
  gateway:
    image: inductiveautomation/ignition:latest
    ports:
      - 8188:8088
      - 8143:8043
    volumes:
      - ./gateway-data:/usr/local/bin/ignition/data
    networks:
      - network  
    environment:
      GATEWAY_ADMIN_PASSWORD_FILE: /run/secrets/gateway-admin-password
      ACCEPT_IGNITION_EULA: "Y"
      IGNITION_EDITION: standard
      TZ: America/Bogota  # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
    secrets:
      - gateway-admin-password
    # Use depends_on to only launch this container if our init container exits cleanly
    depends_on:
      init-gateway:
        condition: service_completed_successfully
    command: >
      -n dau_ind_name

  db:
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network
    environment:
      MYSQL_ROOT_PASSWORD_FILE: run/secrets/db-root-password
      MYSQL_DATABASE: plant 
      MYSQL_USER: dautom
      MYSQL_PASSWORD: password
    secrets:
      - db-root-password
      
secrets:
  gateway-admin-password:
    file: secrets/GATEWAY_ADMIN_PASSWORD_FILE
  db-root-password:
    file: secrets/DB_ROOT_PASSWORD_FILE

volumes:
  mysql_data:

networks:
  network:
